[project]
name = "stormsim"
version = "0.1.6"
description = "A modular coastal storm simulation system for synthetic storm lifecycles and physical impact modeling."
readme = "README.md"
authors = [
    { name = "StormSim Developers" }
]
license = { text = "MIT" }
requires-python = ">=3.8"
dependencies = [
    "requests",
    "numpy",
    "pandas",
    "h5py",
    "scipy",
    "tqdm",
    "duckdb",
    "boto3",
    "s3fs",
    "python-dotenv",
    "pyarrow",
    "pydantic>=2.10.6",
]

[project.urls]
Homepage = "https://github.com/trietmnj/stormsim"
Repository = "https://github.com/trietmnj/stormsim"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["stormsim*"]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.15.13",
    "tables>=3.8.0",
]
